apiVersion: v1
kind: ConfigMap
metadata:
  name: ourfamroots-config
  namespace: ourfamroots
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  S3_REGION: "us-east-1"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis:6379/1"
